- renovate-config: "renovate/default-renovate-distribution.json"
  sync-repositories:
    - name: "red-hat-data-services/rhods-operator"
    - name: "red-hat-data-services/codeflare-operator"
    - name: "red-hat-data-services/odh-dashboard"
    - name: "red-hat-data-services/kubeflow"
    - name: "red-hat-data-services/kuberay"
    - name: "red-hat-data-services/kserve"
    - name: "red-hat-data-services/kueue"
    - name: "red-hat-data-services/data-science-pipelines"
    - name: "red-hat-data-services/ml-metadata"
    - name: "red-hat-data-services/modelmesh"
    - name: "red-hat-data-services/training-operator"
    - name: "red-hat-data-services/trustyai-explainability"
    - name: "red-hat-data-services/data-science-pipelines-operator"
    - name: "red-hat-data-services/model-registry"
    - name: "red-hat-data-services/model-registry-operator"
    - name: "red-hat-data-services/rest-proxy"
    - name: "red-hat-data-services/odh-model-controller"
    - name: "red-hat-data-services/odh-cli"
    - name: "red-hat-data-services/modelmesh-runtime-adapter"
    - name: "red-hat-data-services/modelmesh-serving"
    - name: "red-hat-data-services/trustyai-service-operator"
    - name: "red-hat-data-services/feast"
    - name: "red-hat-data-services/trainer"
    - name: "red-hat-data-services/mlflow"
    - name: "red-hat-data-services/mlflow-operator"
    - name: "red-hat-data-services/vllm-gaudi"
    - name: "red-hat-data-services/mlserver"
    - name: "red-hat-data-services/models-as-a-service"
    - name: "red-hat-data-services/NeMo-Guardrails"
    - name: "red-hat-data-services/eval-hub"
    - name: "red-hat-data-services/workload-variant-autoscaler"
    - name: "red-hat-data-services/llm-d-kv-cache"
    - name: "red-hat-data-services/ai-gateway-payload-processing"
    - name: "red-hat-data-services/pipelines-components"
    - name: "red-hat-data-services/kube-rbac-proxy"
    - name: "red-hat-data-services/ilab-on-ocp"
      targetFilePath: "renovate.json"
    - name: "red-hat-data-services/argo-workflows"
      targetFilePath: "renovate.json"
    - name: "red-hat-data-services/kube-auth-proxy"
      targetFilePath: ".github/renovate.json5"

    - name: "red-hat-data-services/odh-ai-fifth-demo"
- renovate-config: "renovate/custom-renovate-distribution.json"
  sync-repositories:
    - name: "red-hat-data-services/RHOAI-Build-Config"

- renovate-config: "renovate/llama-stack-renovate-distribution.json"
  sync-repositories:
    - name: "red-hat-data-services/llama-stack-distribution"
      targetFilePath: "renovate.json"
